name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name used for the release"

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag_name }}  # Uses the pushed tag name
          name: "Release ${{ inputs.tag_name }}"
          body: "Automated release for version ${{ inputs.tag_name }}"
          draft: true  # Set to true if you want a draft release
          prerelease: false  # Set to true for pre-releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
