name: Create Release

on:
  push:
    tags:
      - '[0-9]{4}.[1-9]|1[0-2].[1-9]|[12][0-9]|3[01].[0-9]+'  # Matches YYYY.M.D.X

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # Uses the pushed tag name
          name: "Release ${{ github.ref_name }}"
          body: "Automated release for version ${{ github.ref_name }}"
          draft: true  # Set to true if you want a draft release
          prerelease: false  # Set to true for pre-releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
