name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    name: Create GitHub Release
    if: ${{ github.ref_type == 'tag' && github.ref =~ 'refs/tags/[0-9]{4}.[0-9]{1,2}.[0-9]{1,2}.[0-9]+$' }} # Ensure stable release only (e.g. 2025.2.18.23)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}  # Uses the pushed tag name
          name: "Release ${{ github.ref_name }}"
          body: "Automated release for version ${{ github.ref_name }}"
          draft: true  # Set to true if you want a draft release
          prerelease: false  # Set to true for pre-releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
