name: Weekly release branch creation

on:
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current date (one week ahead)
        run: |    
          DATE=$(date -d 'next week' +'%Y%m%d')
          YEAR=${DATE:0:4}          # Year: first 4 characters
          MONTH=$((10#${DATE:4:2})) # Month: next 2 characters and remove leading zero from month (e.g. 05 -> 5)
          DAY=$((10#${DATE:6:2}))   # Day: last 2 characters and remove leading zero from day (e.g. 09 -> 9)

          echo "BRANCH_NAME=release/${YEAR}.${MONTH}.${DAY}" >> $GITHUB_ENV
          
      - name: Create new branch
        run: git checkout -b $BRANCH_NAME

      - name: Push new branch
        run: git push origin $BRANCH_NAME
