name: Cong - Pipeline versioning test

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: "Branch name to run pipeline against"
        required: true
        default: "develop"
  push:
    branches: [ "main", "develop", "hotfix/*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    outputs:
      VERSION_TYPE: ${{ steps.version.outputs.version_type }}
      VERSION: ${{ steps.version.outputs.version }}
      BRANCH_NAME: ${{ steps.branch-names.outputs.current_branch }}        
    steps:     
    - name: Checkout branch
      uses: actions/checkout@v4
      # with:
      #   token: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Print event name
      run: |          
        echo "event_name: ${{ github.event_name }}"

    - name: Get branch name
      id: branch-names
      uses: tj-actions/branch-names@v8

    - name: Generate Date-Based Version
      id: version
      run: |
        # Get the current date in YYYYMMDD format
        DATE=$(date +'%Y%m%d')
        YEAR=${DATE:0:4}          # Year: first 4 characters
        MONTH=$((10#${DATE:4:2})) # Month: next 2 characters and remove leading zero from month (e.g. 05 -> 5)
        DAY=$((10#${DATE:6:2}))   # Day: last 2 characters and remove leading zero from day (e.g. 09 -> 9)
        VERSION="${YEAR}.${MONTH}.${DAY}.${GITHUB_RUN_NUMBER}"

        # Get the branch name
        BRANCH_NAME='${{ steps.branch-names.outputs.current_branch }}'
        
        # Check if the ref is a pull request
        PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; /^refs\/pull/ { print $3 }')

        # Determine version type and base version
        if [ "$BRANCH_NAME" = "main" ]
          VERSION_TYPE="stable"
        elif [[ "$BRANCH_NAME" == hotfix* ]]; then
          VERSION_TYPE="hotfix"
          VERSION="${VERSION}-${VERSION_TYPE}"
        elif [[ "$BRANCH_NAME" == release/* ]]; then
          VERSION_TYPE="rc"
          VERSION="${VERSION}-${VERSION_TYPE}"
        elif [ "$BRANCH_NAME" = "develop" ]; then
          VERSION_TYPE="beta"
          VERSION="${VERSION}-${VERSION_TYPE}"
        elif [ -n "$PR_NUMBER" ]; then
          VERSION_TYPE="pr"
          VERSION="${VERSION}-${VERSION_TYPE}-${PR_NUMBER}"
        else
          SAFE_BRANCH=$(echo "$BRANCH_NAME" | tr -cd '[:alnum:]-')
          VERSION_TYPE="branch"
          VERSION="${VERSION}-${VERSION_TYPE}-${SAFE_BRANCH}"
        fi
        echo "VERSION_TYPE=$VERSION_TYPE" >> $GITHUB_OUTPUT
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Tag the commit with the version
      run: |
        git tag ${{ env.version }}
        git push origin ${{ env.version }}        

  release:
    name: Create release
    needs: [build]
    if: needs.build.outputs.VERSION_TYPE == "stable"
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "${{ needs.build.outputs.VERSION }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="Release ${{ needs.build.outputs.VERSION }}" \
              --generate-notes
